In [ ]:
import numpy as np

In [9]:
li=[i for i in range(1,101)]
a= np.array(li)
print(a)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [17]:
a=np.arange(1,101)
b=a.shape
print(b)

(100,)


In [3]:
# using list
import numpy as np
li=[[1,2,3],[4,5,6],[7,8,9]]
np.array(li)

# # using linespace
np.linspace(10,20,6).reshape(3,2)


array([[10., 12.],
       [14., 16.],
       [18., 20.]])

In [26]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
ar1= np.array([1,2,3,4,5])
ar1

ar2= np.array([[1,2,3,4],[5,6,7,8]])
ar2

ar3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
ar3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# numpy

In [4]:
import numpy as np

In [5]:
a=[1,45,78,90]
b= np.array(a)

In [10]:
l1 = [1, 2, 3, 4]
arr = []

for i in l1:
    arr.append(i)
print(arr)

arr = np.array(arr)
arr

[1, 2, 3, 4]


array([1, 2, 3, 4])

## 2d array

In [76]:
arr2d = np.array([[1,2,3], [4,5,6]])
arr2d

arr2d2 = np.array([[1,2,3],[4,5,6]])
print(arr2d2)

[[1 2 3]
 [4 5 6]]


## 3d array

In [ ]:
arr3d = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
arr3d.ndim

arr3d2=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3d2)
arr3d2.ndim

# it tells the no. of dimension of array


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


3

## shape

In [ ]:
## Shape of an array
arr=np.array([[1,2],[3,4]])
print(arr)
arr.shape

# it will tell you the rows and columns of array

[[1 2]
 [3 4]]


(2, 2)

## higher dimensional

In [ ]:
## Higher Dimentional Array
arr = np.array([1,2,3,4,5], ndmin=10)
print(arr)

# ndmin is the attribute of array it gives the dimsionsion

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]


## arrays with zeroes

In [5]:
import numpy as np
## Creating arrays with zeroes (2d) 

zeros = np.zeros((10,5))
zeros

zeros2 = np.zeros([5,6])
zeros2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## zeroes (3d)

In [ ]:
## Creating arrays with zeroes (3d)
zeros3d = np.zeros((1,2,3)) 
zeros3d

zeros3d2=np.zeros((2,3,4))
zeros3d2

# we use three element in this 1st for how many time we want to create the array 2nd for rows and 3rd for the column

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## arrays with ones

In [ ]:
## Similarily for ones
arrones = np.ones((5,6))
arrones

arr2 = np.ones((3,4))
arr2


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

## arrray with ones (3d)

In [9]:
arr3 = np.ones((2,3,4))
arr3

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

## EYE IN ARRAY

In [14]:
## np.eye()---> Identity Matrix --> Diagonal element --> 1
arrI = np.eye(3, dtype=int)
print(arrI)

arr2 = np.eye(6, dtype=str)
print(arr2)

arr3 = np.eye(4, dtype=float)
print(arr3)

arr4 = np.eye(8)
print(arr4)



[[1 0 0]
 [0 1 0]
 [0 0 1]]
[['1' '' '' '' '' '']
 ['' '1' '' '' '' '']
 ['' '' '1' '' '' '']
 ['' '' '' '1' '' '']
 ['' '' '' '' '1' '']
 ['' '' '' '' '' '1']]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [26]:
lst = [i for i in range(2,21,2)]
lst

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

## ARANGE FUNCTION

In [ ]:
## arange function
arr = np.arange(2,20).reshape(6,3)
print(arr)

arr2= np.arange(2,30,3).reshape(2,5)
print(arr2)

arr3 = np.arange(1,40,2).reshape(5,4)
print(arr3)



# Reshape
## Rule --> rows x columns = no. of elements
## in arange 1st is start 2nd is stope 3rd is step
## in reshape 1st is row and 2nd is column

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 2  5  8 11 14]
 [17 20 23 26 29]]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]
 [33 35 37 39]]


## linspace

In [28]:
## Linspace
arr_lin = np.linspace(2,20,10).reshape(5,2)
arr_lin

arr_lin2 = np.linspace(3,30,10).reshape(2,5)
print(arr_lin2)

# linspace 
##  Syntax np.linspace(start, stop(inclusive), no. of elements)
##  linspace is used to divide element in equal parts


[[ 3.  6.  9. 12. 15.]
 [18. 21. 24. 27. 30.]]


In [40]:
## Numpy  ---> axis = 0 --> columns
# axis = 1 --> Rows 

## arithmetic calculation in numpy

In [ ]:
max1=np.arange(2,20).reshape(3,6)
max2=np.arange(22,40).reshape(3,6)

# add
add = max1 + max2
print(add)

# subtract
sub = max1 - max2
print(sub)

# divide
div = max1 / max2
print(div)

# the order must be same of both of the matrix

ValueError: operands could not be broadcast together with shapes (3,6) (6,3) 

## .dot multiply matrix

In [37]:
max1=np.arange(2,20).reshape(3,6)
max2=np.arange(22,40).reshape(6,3)

multi = max1.dot(max2)
print(multi)

# column of 1st matrix must be equal to row of 2nd matrix

[[ 849  876  903]
 [1911 1974 2037]
 [2973 3072 3171]]


## random module

In [ ]:
## random module
np.random.seed(42)  ## fix a random state
np.random.randint(1,100,5)  ## random.randint(start, stop, numbers)

np.random.seed(51)
r=np.random.randint(5,50,10)
print(r)
# in random it gives rendom no. from the given range
# but everytime we we rerun it changes the value
# so if u want to fix that random value seed is used to fix it


[42 37 14 10 21 26 35 46 42 42]


## rand

In [41]:
np.random.rand(5)  

ra=np.random.rand(12)
print(ra)
# it gives the randon numbers between 0 and 1 only

[0.53732654 0.11812258 0.6111332  0.16080176 0.19221861 0.17167441
 0.73107354 0.46710373 0.41442908 0.03080754 0.05875461 0.20837553]


In [43]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.hstack((a,b))
print(c)

d = np.array([1,2,3])
e = np.array([4,5,6])
f = np.vstack((d,e))
print(f)

# hstack is used to add two or more horizontal array
# vstack is used to add two or more vartical array

[1 2 3 4 5 6 7 8]
[[1 2 3]
 [4 5 6]]


## principle of -1

In [27]:
## Principal of -1

arr = np.arange(1,101)
arr.reshape(-1,5)
arr.shape

(100,)